### ISSUE TITLE
No landscape mode

### ISSUE THREAD

**Issue by notspecified** [derqurps/noefinderlein#1]
there is no landscape mode, neither in version 1.0.2  (with android 5.1.1) nor in 1.0.3 (with android n)

**Comment by derqurps** [comment]
I found it not necessary to implement a landscape mode for this app. And also I have very little time developing this app. You are very welcome to develop the feature yourself and send a pull request.

**Comment by notspecified** [comment]
oh, i see... thanks for this offer, i really would love to, but i have no idea of coding! i'm sorry...
