### ISSUE TITLE
back button closes app (unintentionally) -V1.0.2&1.0.3

### ISSUE THREAD

**Issue by notspecified** [derqurps/noefinderlein#3]
when i choose region, favoriten, besichtigte or nahe from the menu and want to switch back afterwards with the "android back button" the app closes.
IMHO this is the wrong action, i would expect to get back to the main screen of the app which is "alle". only a second push on the back button should close the app, resp. then youre on the home screen of the app "back" should close it..

**Comment by derqurps** [comment]
Hmm. I never thought of that, because I saw the navigation drawer (menu on the left) as main menu. And the list as first child. I think I will look into that when I find time.

**Comment by notspecified** [comment]
oh, i see.. you want  to make it similar/identical to the menu in google maps! From this point of view everything makes sense...
